import type {
  CategoryType,
  OrderType,
  PurchaseType,
  Supplier,
  UserType,
} from "./types";
// export const books: BookType[] = [
//   {
//     id: "1",
//     title: "The Midnight Library",
//     author: "Matt Haig",
//     description:
//       "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
//     price: 24.99,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "August 13, 2020",
//     pages: 304,
//     isbn: "9781786892737",
//   },
//   {
//     id: "2",
//     title: "Atomic Habits",
//     author: "James Clear",
//     description:
//       "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
//     price: 27.0,
//     coverImage: coverImage,
//     category: "Self-Help",
//     publishedDate: "October 16, 2018",
//     pages: 320,
//     isbn: "9781847941831",
//   },
//   {
//     id: "3",
//     title: "Project Hail Mary",
//     author: "Andy Weir",
//     description:
//       "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
//     price: 28.99,
//     coverImage: coverImage,
//     category: "Science Fiction",
//     publishedDate: "May 4, 2021",
//     pages: 496,
//     isbn: "9780593135204",
//   },
//   {
//     id: "4",
//     title: "The Four Winds",
//     author: "Kristin Hannah",
//     description:
//       "Texas, 1934. Millions are out of work and a drought has broken the Great Plains. Farmers are fighting to keep their land and their livelihoods as the crops are failing, the water is drying up, and dust threatens to bury them all. One of the darkest periods of the Great Depression, the Dust Bowl era, has arrived with a vengeance.",
//     price: 28.99,
//     coverImage: coverImage,
//     category: "Historical Fiction",
//     publishedDate: "February 2, 2021",
//     pages: 464,
//     isbn: "9781250178602",
//   },
//   {
//     id: "5",
//     title: "Educated",
//     author: "Tara Westover",
//     description:
//       "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent.",
//     price: 28.0,
//     coverImage: coverImage,
//     category: "Memoir",
//     publishedDate: "February 20, 2018",
//     pages: 334,
//     isbn: "9780399590504",
//   },
//   {
//     id: "6",
//     title: "Where the Crawdads Sing",
//     author: "Delia Owens",
//     description:
//       "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say.",
//     price: 26.0,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "August 14, 2018",
//     pages: 384,
//     isbn: "9780735219090",
//   },
//   {
//     id: "7",
//     title: "Becoming",
//     author: "Michelle Obama",
//     description:
//       "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work.",
//     price: 32.5,
//     coverImage: coverImage,
//     category: "Autobiography",
//     publishedDate: "November 13, 2018",
//     pages: 448,
//     isbn: "9781524763138",
//   },
//   {
//     id: "8",
//     title: "The Silent Patient",
//     author: "Alex Michaelides",
//     description:
//       "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
//     price: 26.99,
//     coverImage: coverImage,
//     category: "Thriller",
//     publishedDate: "February 5, 2019",
//     pages: 336,
//     isbn: "9781250301697",
//   },
//   {
//     id: "9",
//     title: "Shadows of Tomorrow",
//     author: "Kathleen Rivera",
//     description:
//       "As the world teeters on the brink of transformation, one decision changes everything. A riveting tale of hope, ambition, and consequence.",
//     price: 32.7,
//     coverImage: coverImage,
//     category: "Autobiography",
//     publishedDate: "February 07, 2022",
//     pages: 365,
//     isbn: "9781973038584",
//   },
//   {
//     id: "10",
//     title: "The Memory Code",
//     author: "Derek Mitchell",
//     description:
//       "Lost in time but preserved in memory, this compelling story uncovers ancient secrets buried beneath layers of emotion and legacy.",
//     price: 25.96,
//     coverImage: coverImage,
//     category: "Memoir",
//     publishedDate: "August 01, 2020",
//     pages: 432,
//     isbn: "9781695214577",
//   },
//   {
//     id: "11",
//     title: "Pathways to Power",
//     author: "Sara Stephens",
//     description:
//       "An inspirational journey through leadership, personal growth, and the pursuit of influence in a rapidly changing world.",
//     price: 22.4,
//     coverImage: coverImage,
//     category: "Self-Help",
//     publishedDate: "February 14, 2020",
//     pages: 305,
//     isbn: "9781843293236",
//   },
//   {
//     id: "12",
//     title: "Echoes in the Fog",
//     author: "Jacqueline Evans",
//     description:
//       "In a town veiled in secrets, one woman must confront a haunting past that refuses to stay hidden.",
//     price: 22.14,
//     coverImage: coverImage,
//     category: "Thriller",
//     publishedDate: "May 30, 2020",
//     pages: 547,
//     isbn: "9781399982899",
//   },
//   {
//     id: "13",
//     title: "Silent Resistance",
//     author: "Richard Collins",
//     description:
//       "An epic of quiet rebellion against tyranny, where resilience and courage change the fate of a generation.",
//     price: 27.7,
//     coverImage: coverImage,
//     category: "Historical Fiction",
//     publishedDate: "November 22, 2016",
//     pages: 369,
//     isbn: "9781736511355",
//   },
//   {
//     id: "14",
//     title: "The Final Signal",
//     author: "Jeffrey Gutierrez",
//     description:
//       "When the last transmission is received from a distant galaxy, a lone astronaut unravels the mysteries of humanity's origins.",
//     price: 21.2,
//     coverImage: coverImage,
//     category: "Science Fiction",
//     publishedDate: "March 09, 2018",
//     pages: 343,
//     isbn: "9781291681873",
//   },
//   {
//     id: "15",
//     title: "Legacy of the Lost",
//     author: "Margaret Watts",
//     description:
//       "A gripping saga of discovery, love, and the powerful bonds that tie generations together across continents.",
//     price: 24.66,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "October 04, 2020",
//     pages: 323,
//     isbn: "9781249992072",
//   },
//   {
//     id: "16",
//     title: "A Glimpse Beyond",
//     author: "Christopher Salazar",
//     description:
//       "A gripping exploration into the unknown, where metaphysics and emotion collide in a quest for the truth.",
//     price: 25.97,
//     coverImage: coverImage,
//     category: "Fantasy",
//     publishedDate: "January 20, 2021",
//     pages: 370,
//     isbn: "9781354070035",
//   },
//   {
//     id: "17",
//     title: "Unwritten Truths",
//     author: "Catherine Allen",
//     description:
//       "Behind every smile lies a truth unspoken. A stirring narrative about family secrets and personal reckoning.",
//     price: 24.6,
//     coverImage: coverImage,
//     category: "Memoir",
//     publishedDate: "February 17, 2024",
//     pages: 450,
//     isbn: "9781377274293",
//   },
//   {
//     id: "18",
//     title: "The Art of Falling",
//     author: "Vincent Fuller",
//     description:
//       "In the graceful collapse of a dancer’s world, he finds himself rebuilding from the beauty of imperfection.",
//     price: 27.39,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "August 08, 2017",
//     pages: 474,
//     isbn: "9781743312172",
//   },
//   {
//     id: "19",
//     title: "Beneath the Ashes",
//     author: "April Delgado",
//     description:
//       "Tragedy strikes a small town, but hope rises from the ashes as one woman seeks answers to her family’s fate.",
//     price: 20.68,
//     coverImage: coverImage,
//     category: "Mystery",
//     publishedDate: "June 12, 2015",
//     pages: 406,
//     isbn: "9781799095281",
//   },
//   {
//     id: "20",
//     title: "The Forsaken Shore",
//     author: "Terry Bates",
//     description:
//       "A voyage to an uncharted land leads to unexpected danger and truths buried beneath ancient waters.",
//     price: 24.9,
//     coverImage: coverImage,
//     category: "Science Fiction",
//     publishedDate: "December 04, 2023",
//     pages: 349,
//     isbn: "9781135948563",
//   },
//   {
//     id: "21",
//     title: "Waves of Deception",
//     author: "Cory Chambers",
//     description:
//       "Nothing is as it seems on the coast of Maine, where old secrets stir beneath the tide of a deadly game.",
//     price: 29.37,
//     coverImage: coverImage,
//     category: "Thriller",
//     publishedDate: "October 03, 2019",
//     pages: 397,
//     isbn: "9781449072846",
//   },
//   {
//     id: "22",
//     title: "The Last Embrace",
//     author: "Jenna Leonard",
//     description:
//       "A romance tested by war and circumstance, this heart-wrenching story explores love's power to endure the impossible.",
//     price: 25.58,
//     coverImage: coverImage,
//     category: "Historical Fiction",
//     publishedDate: "June 26, 2017",
//     pages: 459,
//     isbn: "9781629728549",
//   },
//   {
//     id: "23",
//     title: "Fragments of Us",
//     author: "Nathaniel Cohen",
//     description:
//       "They had everything—until they didn’t. A story of relationships, regret, and the pieces we try to put back together.",
//     price: 23.65,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "January 13, 2022",
//     pages: 480,
//     isbn: "9780358434931",
//   },
//   {
//     id: "24",
//     title: "When We Were Wild",
//     author: "Joan Francis",
//     description:
//       "Set against the backdrop of a summer that changed everything, this coming-of-age novel explores freedom and consequence.",
//     price: 21.42,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "July 16, 2021",
//     pages: 340,
//     isbn: "9780063206337",
//   },
//   {
//     id: "25",
//     title: "Voices from the Edge",
//     author: "Todd Figueroa",
//     description:
//       "True stories from survivors, pioneers, and misfits, reminding us that the edge is not the end—but a beginning.",
//     price: 23.42,
//     coverImage: coverImage,
//     category: "Biography",
//     publishedDate: "March 27, 2020",
//     pages: 498,
//     isbn: "9781891512811",
//   },
//   {
//     id: "26",
//     title: "Gravity’s Kiss",
//     author: "Amanda Carlson",
//     description:
//       "Two lovers defy space and time in this lyrical tale where physics meets passion in an interstellar world.",
//     price: 25.82,
//     coverImage: coverImage,
//     category: "Science Fiction",
//     publishedDate: "June 24, 2023",
//     pages: 388,
//     isbn: "9781999280933",
//   },
//   {
//     id: "27",
//     title: "Tides of Hope",
//     author: "Arthur Jensen",
//     description:
//       "With every crashing wave, she finds a reason to stay. A story of rebuilding life after loss in a seaside town.",
//     price: 27.8,
//     coverImage: coverImage,
//     category: "Fiction",
//     publishedDate: "October 31, 2021",
//     pages: 377,
//     isbn: "9780689878747",
//   },
//   {
//     id: "28",
//     title: "Blueprints of Destiny",
//     author: "Yvette Barnett",
//     description:
//       "In a world where futures are designed, one woman must find her own path or become a product of someone else’s plan.",
//     price: 33.63,
//     coverImage: coverImage,
//     category: "Fantasy",
//     publishedDate: "February 10, 2016",
//     pages: 491,
//     isbn: "9781449490848",
//   },
// ];

export const orders: OrderType[] = [
  {
    id: "ORD-1001",
    orderDate: "2023-01-15T08:30:00Z",
    total: 125.99,
    status: "Completed",
    items: 3,
    user: {
      name: "John Smith",
      email: "john.smith@example.com",
    },
  },
  {
    id: "ORD-1002",
    orderDate: "2023-01-16T14:22:10Z",
    total: 89.5,
    status: "Shipped",
    items: 2,
    user: {
      name: "Emily Johnson",
      email: "emily.j@example.com",
    },
  },
  {
    id: "ORD-1003",
    orderDate: "2023-01-17T09:45:33Z",
    total: 234.75,
    status: "Processing",
    items: 5,
    user: {
      name: "Michael Brown",
      email: "michael.b@example.com",
    },
  },
  {
    id: "ORD-1004",
    orderDate: "2023-01-18T16:10:21Z",
    total: 56.2,
    status: "Completed",
    items: 1,
    user: {
      name: "Sarah Williams",
      email: "sarah.w@example.com",
    },
  },
  {
    id: "ORD-1005",
    orderDate: "2023-01-19T11:05:44Z",
    total: 178.3,
    status: "Cancelled",
    items: 4,
    user: {
      name: "David Lee",
      email: "david.lee@example.com",
    },
  },
  {
    id: "ORD-1006",
    orderDate: "2023-01-20T13:33:15Z",
    total: 299.99,
    status: "Shipped",
    items: 6,
    user: {
      name: "Jennifer Davis",
      email: "jennifer.d@example.com",
    },
  },
  {
    id: "ORD-1007",
    orderDate: "2023-01-21T10:12:09Z",
    total: 42.5,
    status: "Completed",
    items: 2,
    user: {
      name: "Robert Wilson",
      email: "robert.w@example.com",
    },
  },
  {
    id: "ORD-1008",
    orderDate: "2023-01-22T17:45:30Z",
    total: 155.75,
    status: "Processing",
    items: 3,
    user: {
      name: "Lisa Martinez",
      email: "lisa.m@example.com",
    },
  },
  {
    id: "ORD-1009",
    orderDate: "2023-01-23T12:30:18Z",
    total: 210.0,
    status: "Shipped",
    items: 4,
    user: {
      name: "Thomas Anderson",
      email: "thomas.a@example.com",
    },
  },
  {
    id: "ORD-1010",
    orderDate: "2023-01-24T09:15:42Z",
    total: 87.25,
    status: "Completed",
    items: 2,
    user: {
      name: "Amanda Taylor",
      email: "amanda.t@example.com",
    },
  },
  {
    id: "ORD-1011",
    orderDate: "2023-01-25T15:20:55Z",
    total: 134.6,
    status: "Processing",
    items: 3,
    user: {
      name: "Christopher Garcia",
      email: "chris.g@example.com",
    },
  },
  {
    id: "ORD-1012",
    orderDate: "2023-01-26T11:40:33Z",
    total: 65.99,
    status: "Cancelled",
    items: 1,
    user: {
      name: "Jessica Rodriguez",
      email: "jessica.r@example.com",
    },
  },
  {
    id: "ORD-1013",
    orderDate: "2023-01-27T14:55:12Z",
    total: 189.45,
    status: "Shipped",
    items: 5,
    user: {
      name: "Daniel Hernandez",
      email: "daniel.h@example.com",
    },
  },
  {
    id: "ORD-1014",
    orderDate: "2023-01-28T10:25:47Z",
    total: 72.3,
    status: "Completed",
    items: 2,
    user: {
      name: "Michelle Lopez",
      email: "michelle.l@example.com",
    },
  },
  {
    id: "ORD-1015",
    orderDate: "2023-01-29T13:15:29Z",
    total: 225.8,
    status: "Processing",
    items: 4,
    user: {
      name: "Matthew Gonzalez",
      email: "matt.g@example.com",
    },
  },
  {
    id: "ORD-1016",
    orderDate: "2023-01-30T16:40:18Z",
    total: 110.5,
    status: "Shipped",
    items: 3,
    user: {
      name: "Ashley Perez",
      email: "ashley.p@example.com",
    },
  },
  {
    id: "ORD-1017",
    orderDate: "2023-01-31T12:05:36Z",
    total: 95.25,
    status: "Completed",
    items: 2,
    user: {
      name: "Andrew Sanchez",
      email: "andrew.s@example.com",
    },
  },
  {
    id: "ORD-1018",
    orderDate: "2023-02-01T09:50:22Z",
    total: 310.75,
    status: "Processing",
    items: 7,
    user: {
      name: "Stephanie Ramirez",
      email: "stephanie.r@example.com",
    },
  },
  {
    id: "ORD-1019",
    orderDate: "2023-02-02T14:18:40Z",
    total: 68.9,
    status: "Shipped",
    items: 2,
    user: {
      name: "James Flores",
      email: "james.f@example.com",
    },
  },
  {
    id: "ORD-1020",
    orderDate: "2023-02-03T11:30:15Z",
    total: 142.35,
    status: "Completed",
    items: 3,
    user: {
      name: "Elizabeth Torres",
      email: "elizabeth.t@example.com",
    },
  },
];
export const user: UserType = {
  id: 45,
  name: "Najma Yusuf",
  username: "najmayusuf",
  email: "najmayusuf@gmail.com",
  password: "123456",
  role: "ADMIN",
  avatar: "https://example.com/avatar.jpg",
  phone: "123-456-7890",
  street: "123 Main St",
  city: "Anytown",
  state: "CA",
  zip: "12345",
  country: "USA",
  createdAt: "2023-01-01T00:00:00Z",
  updatedAt: "2023-01-01T00:00:00Z",
};

export const suppliers: Supplier[] = [
  {
    id: 1,
    name: "Global Food Supply",
    contactName: "Emily Carter",
    email: "emily@globalfood.com",
    phone: "+1-555-123-4567",
    address: "123 Elm St, Springfield, IL",
  },
  {
    id: 2,
    name: "Fresh Farms Ltd",
    contactName: "Liam Johnson",
    email: "liam@freshfarms.com",
    phone: "+1-555-987-6543",
    address: "456 Maple Ave, Austin, TX",
  },
  {
    id: 3,
    name: "Sunrise Beverages",
    contactName: "Olivia Smith",
    email: "olivia@sunrisebev.com",
    phone: "+1-555-202-9988",
    address: "789 Oak Blvd, Miami, FL",
  },
  {
    id: 4,
    name: "Ocean Catch",
    contactName: "Noah Davis",
    email: "noah@oceancatch.com",
    phone: "+1-555-303-5566",
    address: "12 Harbor Way, Seattle, WA",
  },
  {
    id: 5,
    name: "Green Valley Produce",
    contactName: "Sophia Brown",
    email: "sophia@greenvalley.com",
    phone: "+1-555-111-2233",
    address: "77 Garden Rd, Portland, OR",
  },
  {
    id: 6,
    name: "Urban Grains Co",
    contactName: "James Wilson",
    email: "james@urbangrains.com",
    phone: "+1-555-222-3344",
    address: "89 Mill St, Chicago, IL",
  },
  {
    id: 7,
    name: "Cocoa Delights",
    contactName: "Mia Taylor",
    email: "mia@cocoadelights.com",
    phone: "+1-555-333-4455",
    address: "66 Cocoa Dr, San Diego, CA",
  },
  {
    id: 8,
    name: "Herbal Essence Traders",
    contactName: "Benjamin Anderson",
    email: "ben@herbalessence.com",
    phone: "+1-555-444-5566",
    address: "101 Forest Ln, Denver, CO",
  },
  {
    id: 9,
    name: "Daily Dairy Co.",
    contactName: "Charlotte Martinez",
    email: "charlotte@dailydairy.com",
    phone: "+1-555-555-6677",
    address: "23 Cowpath Rd, Madison, WI",
  },
  {
    id: 10,
    name: "Bakers' Choice",
    contactName: "William Thomas",
    email: "william@bakerschoice.com",
    phone: "+1-555-666-7788",
    address: "19 Flour St, Boston, MA",
  },
  {
    id: 11,
    name: "Spice World",
    contactName: "Amelia Moore",
    email: "amelia@spiceworld.com",
    phone: "+1-555-777-8899",
    address: "88 Pepper Ln, Houston, TX",
  },
  {
    id: 12,
    name: "Frozen Kingdom",
    contactName: "Elijah Lee",
    email: "elijah@frozenkingdom.com",
    phone: "+1-555-888-9900",
    address: "55 Glacier Dr, Anchorage, AK",
  },
  {
    id: 13,
    name: "Tropical Fruits Inc.",
    contactName: "Harper Perez",
    email: "harper@tropicalfruits.com",
    phone: "+1-555-999-0011",
    address: "70 Pineapple St, Tampa, FL",
  },
  {
    id: 14,
    name: "Gourmet Imports",
    contactName: "Lucas White",
    email: "lucas@gourmetimports.com",
    phone: "+1-555-000-1122",
    address: "10 Market Square, New York, NY",
  },
  {
    id: 15,
    name: "Essential Oils & Spices",
    contactName: "Evelyn Harris",
    email: "evelyn@essentialspices.com",
    phone: "+1-555-121-3344",
    address: "44 Aroma Rd, Phoenix, AZ",
  },
];

export const purchases: PurchaseType[] = [
  {
    id: 1,
    purchaseDate: "2025-01-05",
    total: 1250.5,
    notes: "Bulk order for January stock.",
    supplier: { name: "Fresh Farm Supplies", email: "contact@freshfarm.com" },
  },
  {
    id: 2,
    purchaseDate: "2025-01-10",
    total: 780.0,
    notes: "Weekly supply delivery.",
    supplier: { name: "GreenLeaf Traders", email: "info@greenleaf.com" },
  },
  {
    id: 3,
    purchaseDate: "2025-01-15",
    total: 965.75,
    notes: "Frozen goods delivery.",
    supplier: { name: "Oceanic Foods", email: "sales@oceanicfoods.com" },
  },
  {
    id: 4,
    purchaseDate: "2025-01-18",
    total: 520.0,
    notes: "Urgent spice refill.",
    supplier: {
      name: "Spice Masters Ltd.",
      email: "orders@spicemasters.com",
    },
  },
  {
    id: 5,
    purchaseDate: "2025-01-22",
    total: 1120.25,
    notes: "Monthly dairy supplies.",
    supplier: { name: "Dairy Best", email: "support@dairybest.com" },
  },
  {
    id: 6,
    purchaseDate: "2025-01-27",
    total: 1395.9,
    notes: "Grain and rice stock.",
    supplier: { name: "Golden Harvest", email: "grain@goldenharvest.com" },
  },
  {
    id: 7,
    purchaseDate: "2025-02-02",
    total: 780.0,
    notes: "Vegetable shipment.",
    supplier: { name: "Farm Fresh Co.", email: "hello@farmfresh.co" },
  },
  {
    id: 8,
    purchaseDate: "2025-02-06",
    total: 340.0,
    notes: "Essential oils and herbs.",
    supplier: { name: "Herbal Essence", email: "contact@herbalessence.com" },
  },
  {
    id: 9,
    purchaseDate: "2025-02-11",
    total: 1020.0,
    notes: "Seafood stock.",
    supplier: { name: "SeaCatch Ltd.", email: "fish@seacatch.com" },
  },
  {
    id: 10,
    purchaseDate: "2025-02-14",
    total: 875.65,
    notes: "Baking supplies.",
    supplier: { name: "BakePro", email: "orders@bakepro.com" },
  },
  {
    id: 11,
    purchaseDate: "2025-02-18",
    total: 1200.0,
    notes: "Monthly fruit delivery.",
    supplier: { name: "Fruitopia", email: "fresh@fruitopia.com" },
  },
  {
    id: 12,
    purchaseDate: "2025-02-22",
    total: 1350.1,
    notes: "Imported gourmet items.",
    supplier: { name: "Gourmet World", email: "contact@gourmetworld.com" },
  },
  {
    id: 13,
    purchaseDate: "2025-02-26",
    total: 445.8,
    notes: "Short-term supplement order.",
    supplier: { name: "NutriPlus", email: "sales@nutriplus.com" },
  },
  {
    id: 14,
    purchaseDate: "2025-03-01",
    total: 1499.99,
    notes: "Monthly bulk purchase.",
    supplier: { name: "BulkBuyers", email: "bulk@bulkbuyers.com" },
  },
  {
    id: 15,
    purchaseDate: "2025-03-04",
    total: 890.0,
    notes: "Organic farm produce.",
    supplier: { name: "EcoFarms", email: "organic@ecofarms.com" },
  },
  {
    id: 16,
    purchaseDate: "2025-03-08",
    total: 500.0,
    notes: "Essential pantry items.",
    supplier: { name: "Pantry Hub", email: "service@pantryhub.com" },
  },
  {
    id: 17,
    purchaseDate: "2025-03-11",
    total: 300.5,
    notes: "Special spice blend trial.",
    supplier: {
      name: "Spice Masters Ltd.",
      email: "orders@spicemasters.com",
    },
  },
  {
    id: 18,
    purchaseDate: "2025-03-14",
    total: 945.75,
    notes: "Cheese and dairy order.",
    supplier: { name: "Dairy Best", email: "support@dairybest.com" },
  },
  {
    id: 19,
    purchaseDate: "2025-03-17",
    total: 1340.0,
    notes: "Frozen seafood package.",
    supplier: { name: "Oceanic Foods", email: "sales@oceanicfoods.com" },
  },
  {
    id: 20,
    purchaseDate: "2025-03-20",
    total: 620.3,
    notes: "Fruit and beverage combo.",
    supplier: { name: "Fresh Farm Supplies", email: "contact@freshfarm.com" },
  },
];

// Sample categories
export const bookCategories: CategoryType[] = [
  {
    id: 1,
    name: "Fiction",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Non-Fiction",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Science Fiction",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Fantasy",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Biography",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Self-Help",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "History",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Mystery",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Romance",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Thriller",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: "Horror",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: "Poetry",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: "Children's Books",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: "Young Adult",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: "Comics & Graphic Novels",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 16,
    name: "Cookbooks",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 17,
    name: "Travel",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 18,
    name: "Religion & Spirituality",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 19,
    name: "Science & Technology",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 20,
    name: "Art & Photography",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
